version: 0.1.0                                            

name: Create a repo for Next.js + GitHub Pages - by YOURNAME 
description: A stack to create a repo for a Next.js website that's deployed to Github Pages               

branding:                                          # stack branding 
 icon: 'package'
 color: 'black'

inputs:                                            # stack inputs 
  - name: NODE_VERSION                             # stack input name
    default: v12.22.4                                 # default value
    description: Node version for the Node.js stack   # description
    validvalues:                                      # values that can be selected
    - v12.22.4
    - v14.17.4

configs:
  repo-metadata:
    parameters:
      description: 'Next.js app on GitHub Pages'   # repo description
      topics:                                      # topics for the new repo
      - nextjs
      - github-pages

  environments:
    - name: development                            # create a 'development' environment
      parameters:                                  # environment configuration options 
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*

init:
  uses: "stack-init.yml"                          # specify the initialization file
