name: Deploy to Github Pages
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    name: Deploys the Next.js application
    runs-on: ubuntu-latest

    environment:
      name: development
      url: ${{ steps.get-url.outputs.your_site }}

    steps:
      - name: 1 - Checkout the repository
        uses: actions/checkout@v2
      
      - name: 2 - Use the Node.js version specified in the .nvmrc file
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: 3 - Prepare the application for deployment
        run: |
          npm install
          npm run build
          npm run env -- next export -o build

      - name: 4 - Deploy the application
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true

      - name: 5 - Print the website URL
        run: |
          echo "Website URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"

      - name: 6 - Allow a maximum of 15 minutes for the website to become available
        timeout-minutes: 15
        id: get-url
        run: |
          echo "Waiting for the GitHub Pages website to be available ..."
          URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          sleep 20
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
          echo "STATUSCODE: $STATUS_CODE"
          while [ $STATUS_CODE -ne 200 ]
          do
            sleep 10
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
            echo "STATUSCODE: $STATUS_CODE"
          done
          echo "The application is now running and available to use."
          echo "Browse here: $URL"
          echo "::set-output name=your_site::$URL"
